# datasource config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/classy
    username: classy
    password: classy##


  # jpa config
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # file upload size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


# server port
server:
  port: 8002

# image file
image:
  image-url: http://localhost:8001/imgs/
  image-dir: src/main/resources/static/imgs


# jwt setting
# ????? 1????(3600000?)
# secret? ???? ???? ??
# ???? ?? ????? 1??(604800000?)
jwt:
  secret: 6Ihu7rKPxL8Gl9lWDJyLYkTIraYFCjDIjO27z497/EZY8+QOOtYe50R7gM8KWluw/VFX/38fBp3nUPf3p589mKUz5/wtwq8UA9sgx/lfqPi/wEyuGTSfIC0eEqVd2eLRw9rQq7Mtbb9F9cTMVU2vxEvZHdfH22oR7Elkak3Xo7kO8iVmrxnq8ou7FsTHwox74x3nWV3wyF9ikJdKxGUQ+0uc4mdccGCew9wo9Q==
  access:
    expiration: 3600000
  #    expiration: 1000
  refresh:
    expiration: 604800000
